FROM php:8.1-cli

COPY --from=composer /usr/bin/composer /usr/bin/composer
RUN apt-get update
RUN apt-get install -y \
        libzip-dev \
        zip \
        && docker-php-ext-install zip

RUN chmod +x /usr/bin/composer
